name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    # Java 17 setup
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # Configure and setup Gradle
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3.1.0
      
    # Build Spring Boot application
    - name: Build with Gradle Wrapper
      run: ./gradlew build
      
    # Docker image build
    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/ggamanggarden-parentsday .

    # DockerHub login
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    # Push Docker image to Docker Hub
    - name: Push Docker image to Docker Hub
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/ggamanggarden-parentsday

  dependency-submission:
    needs: build-and-push-docker-image
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    
    # Dependency submission
    - name: Submit dependency graph
      uses: gradle/actions/dependency-submission@v3.1.0

  run-docker-image-on-ec2:
    needs: dependency-submission
    runs-on: [self-hosted]
    steps:
      # Pull the latest image
      - name: Pull latest Docker image
        run: sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/ggamanggarden-parentsday

      # Stop existing container
      - name: Stop existing Docker container
        run: sudo docker stop $(sudo docker ps -q) || true

      # Run new container
      - name: Run new Docker container
        run: sudo docker run --name ggamanggarden-parentsday --rm -d -p 8080:8080 ${{ secrets.DOCKERHUB_USERNAME }}/ggamanggarden-parentsday

      # Cleanup unused Docker images
      - name: Clean up old Docker images
        run: sudo docker system prune -a -f
