name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    # Java 17 setup
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # Modify properties file
    - name: Modify properties file
      run: |
        sed -i "s|spring.profiles.active=local|spring.profiles.active=prod|" ./src/main/resources/application.properties

    # Modify properties-prod file 
    - name: Modify properties-prod file
      run: |
        sed -i "s|#spring.datasource.username=|spring.datasource.username=${{ secrets.DB_USERNAME }}|" ./src/main/resources/application-prod.properties
        sed -i "s|#spring.datasource.password=|spring.datasource.password=${{ secrets.DB_PASSWORD }}|" ./src/main/resources/application-prod.properties
        sed -i "s|#coolsms.api.key=|coolsms.api.key=${{ secrets.COOLSMS_KEY }}|" ./src/main/resources/application-prod.properties
        sed -i "s|#coolsms.api.secret=|coolsms.api.secret=${{ secrets.COOLSMS_SECRET }}|" ./src/main/resources/application-prod.properties
          
    # Configure and setup Gradle
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3.1.0
      
    # Build Spring Boot application
    - name: Build with Gradle Wrapper
      run: ./gradlew build
      
    # Docker image build
    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/ggamanggarden-parentsday .

    # DockerHub login
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    # Push Docker image to Docker Hub
    - name: Push Docker image to Docker Hub
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/ggamanggarden-parentsday

  run-docker-image-on-ec2:
    needs: build-and-push-docker-image
    runs-on: ubuntu-latest
    steps:
      - name: Executing remote SSH commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ec2-user
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/ggamanggarden-parentsday
            sudo docker stop $(sudo docker ps -q) || true
            sudo docker run --name ggamanggarden-parentsday --rm -d -p 8080:8080 ${{ secrets.DOCKERHUB_USERNAME }}/ggamanggarden-parentsday
            sudo docker system prune -a -f
